# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Yiwei Zuo(左绎未)"
description              : "Computer Science and Technology Undergraduate at Beijing Jiaotong University. "
repository               : "YiweiZuo/YiweiZuo.github.io"
google_scholar_stats_use_cdn : false  # Changed to false since you don't have Google Scholar yet

# google analytics
google_analytics_id      : # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
# google_site_verification :  # Commented out as not needed yet
# bing_site_verification   :  # Commented out as not needed yet
# baidu_site_verification  :  # Commented out as not needed yet

# Site Author
author:
  name   : "Yiwei Zuo"
  avatar : "images/android-chrome-512x512.png"
  bio    : "Computer Science and Technology"
  #location         : "Beijing, China"
  # employer         :  # Commented out as not needed yet
  # pubmed           :  # Commented out as not needed yet
  # googlescholar    :  # Commented out as not needed yet
  email            : "ywz659789@gmail.com"
  # researchgate     :  # Commented out as not needed yet
  # uri              :  # Commented out as not needed yet
  # bitbucket        :  # Commented out as not needed yet
  # codepen          :  # Commented out as not needed yet
  # dribbble         :  # Commented out as not needed yet
  # flickr           :  # Commented out as not needed yet
  # facebook         :  # Commented out as not needed yet
  # foursquare       :  # Commented out as not needed yet
  github           : "yiweizuo"
  # google_plus      :  # Commented out as not needed yet
  # keybase          :  # Commented out as not needed yet
  # instagram        :  # Commented out as not needed yet
  # impactstory      :  # Commented out as not needed yet
  # lastfm           :  # Commented out as not needed yet
  # linkedin         :  # Commented out as not needed yet
  # dblp             :  # Commented out as not needed yet
  # orcid            :  # Commented out as not needed yet
  # pinterest        :  # Commented out as not needed yet
  # soundcloud       :  # Commented out as not needed yet
  # stackoverflow    :  # Commented out as not needed yet
  # steam            :  # Commented out as not needed yet
  # tumblr           :  # Commented out as not needed yet
  # twitter          :  # Commented out as not needed yet
  # vine             :  # Commented out as not needed yet
  # weibo            :  # Commented out as not needed yet
  # xing             :  # Commented out as not needed yet
  # youtube          :  # Commented out as not needed yet
  # wikipedia        :  # Commented out as not needed yet


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
